orm_abc_app/urls.py
from django.urls import path

from . import views

app_name = 'orm_abc_app'
urlpatterns = [
    path('', views.index, name='index'),
    path('datetime_nov/', views.datetime_nov, name='datetime_nov'),
    path('var_list_dict/', views.var_list_dict, name='var_list_dict'),
    path('abc_form/', views.abc_form, name='abc_form'),
    path('abc_get/', views.abc_get, name='abc_get'),
    path('form_create_0/', views.form_create_0, name='form_create_0'),
    path('form_create/', views.form_create, name='form_create'),
    path('abc_result/', views.abc_result, name='abc_result'),
    path('table/', views.table, name='table'),
]

orm_abc_prj/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('orm_abc_app/', include('orm_abc_app.urls')),
    path('', include('orm_abc_app.urls')),
]

orm_abc_app/models.py
# import datetime
from django.db import models

c_choices = (
    (0, "ноль"),
    (10, "десять"),
    (15, "пятнадцать"),
    (20, "двадцать"),
)


class Abc(models.Model):
    task = models.CharField(verbose_name="Формулировка  задачи", default="1/(XY) равно ?", max_length=255)
    x = models.IntegerField(verbose_name="Значение X", default=0 )
    y = models.IntegerField(verbose_name="Значение Y", default=0, help_text="Подсказка для поля Y")
    # z = models.IntegerField(verbose_name="Значение Z", choices=c_choices, default=0 )
    current_date = models.DateTimeField(verbose_name="Дата изменения(save)", auto_now=True)

    def __str__(self):
        # return self.task
        # return '%s %s' % (self.task, self.current_date)
        return f"{self.id}&{self.task}"


    class Meta:
        verbose_name = "Z_Y_Z"
        verbose_name_plural = "X_Y_Z_S"
        ordering = ('-id', '-x')




# current_date = models.DateTimeField("ДатаВремя", default=datetime.datetime.now())
# current_date = models.DateTimeField("ДатаВремя", auto_now_add=True)


# python manage.py makemigrations
# python manage.py migrate


# admin.py
# from django.contrib import admin
# # Register your models here.
# from .models import Abc
# admin.site.register(Abc)


# forms.py
# from django.forms import ModelForm
# from .models import Abc
#
# class CreateAbcForm(ModelForm):
#     class Meta:
#         model = Abc
#         fields = ['task', 'a' ,'b' ,'c', 'c_calc']

orm_abc_app/forms.py
from django import forms
from django.forms import ModelForm
from .models import Abc


class CreateAbcForm(ModelForm):
    # task = forms.CharField(widget=forms.Textarea({'cols': '60', 'rows': "3"}))
    # task.widget.attrs.update({'cols': '40', 'rows': "2"})
    class Meta:
        model = Abc
        fields = '__all__'
        # fields = ['task', 'a', 'b','c']
        print('\nfields: ', fields)

orm_abc_app/views.py
import datetime
from django import forms
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.db.models import Count, Avg, Min, Max, StdDev, Sum
from .forms import CreateAbcForm
from .models import Abc

def index(request):
    return render(request, 'index.html')

def datetime_nov(request):
    datetime_now = datetime.datetime.now()
    print(datetime_now)
    context = {'key': datetime_now}
    return render(request, 'datetime_now.html', context)


def var_list_dict(request):
    var_main = 2
    print(var_main)
    list_main = [1, 2, 3, 4, 5]
    print(list_main)
    dict_main = {'x': 1, 'y': 2}
    print(dict_main)
    context = {"var_main": var_main, 'list_main': list_main, 'dict_main': dict_main}
    return render(request, 'list_dict.html', context)

class AbcFormCreate(forms.Form):
    a = forms.IntegerField(initial=1, min_value=2)
    b = forms.IntegerField(required=False)
    c = forms.IntegerField(label='c_lable')


def abc_form(request):
    abc_form = AbcFormCreate()
    print(abc_form)
    return render(request, 'abc_form.html', {"abc_form": abc_form})


def abc_get(request):
    print(request.GET)
    print(request.GET.get("x"))
    print(request.GET.get("y"))
    print(request.GET.get("z"))
    X = request.GET.get("x")
    Y = request.GET.get("y")
    Z = request.GET.get("z")
    return HttpResponse(f"""
    <pre>
    X = {X}
    Y = {Y}
    Z = {Z}
    </pre>
    """)



def form_create_0(request):
    print('request.method: ', request.method)
    if request.method == 'POST':
        form = CreateAbcForm(request.POST)
        if form.is_valid():
            print("\nform_is_valid:\n", form)
            form.save()
            return redirect('orm_abc_app:abc_result')
    else:
        form = CreateAbcForm()
        print('\nform_else:\n', form)
    context = {'form': form}
    print("\ncontext:\n", context)
    return render(request, 'form_create_0.html', context)


def form_create(request):
    print('request.method: ', request.method)
    if request.method == 'POST':
        form = CreateAbcForm(request.POST)
        if form.is_valid():
            print("\nform_is_valid:\n", form)
            form.save()
            return redirect('orm_abc_app:abc_result')
    else:
        form = CreateAbcForm()
        print('\nform_else:\n', form)
    context = {'form': form}
    print("\ncontext:\n", context)
    return render(request, 'form_create.html', context)


def abc_result(request):
    object_list = Abc.objects.all().order_by('-id')[:2]
    # print("object_list: ", object_list)
    # dict
    # print("object_list.values('x', 'y', 'z'):", object_list.values('x', 'y', 'z'))
    last_object = object_list.values('x', 'y')[0]
    # print("last_object: ", last_object)
    # print("object_0_a: ", last_object['x'])
    # list
    values_list = object_list.values_list()[0]
    # print("values_list: ", values_list)
    # if values_list[2] + values_list[3] == values_list[4]:
    #     result = "1/(XY) равно"
    # else:
    #     result = "1/(XY) равно"
    # context
    task_formulation = values_list[1]
    # print('task_content: ', task_formulation)
    last_data = [values_list[2], values_list[3]]
    # print('last_data:', last_data)
    # print('result: ', result)
    # print(last_object['x'])

    if last_object['x'] != 0 and last_object['y'] != 0:
        result = str(1 / (last_object['x'] * last_object['y']))
    else:
        result = "Результат не определен"

    context = {'task_formulation': task_formulation, 'last_data': last_data, 'result': result, 'last_object': last_object}
    return render(request, 'abc_result.html', context)


def table(request):
    # objects_list
    objects_values = Abc.objects.values()
    print('\nobjects_values:', objects_values)
    # values_list 
    objects_values_list = Abc.objects.values_list()
    print('\nobjects_values_list:', objects_values_list)
    cur_objects = Abc.objects.all()
    statics_val = [cur_objects.aggregate(Count('y')), cur_objects.aggregate(Avg('y')), cur_objects.aggregate(Min('y')),
                   cur_objects.aggregate(Max('y')), cur_objects.aggregate(StdDev('y')), cur_objects.aggregate(Sum('y'))]
    print('\nstatics_val:', statics_val)
    statics = {'statics_val': statics_val}
    # fields_name
    fields = Abc._meta.get_fields()
    print('\nfields', fields)
    verbose_name_list = []
    name_list = []
    for e in fields:
        verbose_name_list.append(e.verbose_name)
        name_list.append(e.name)
    print('\nverbose_name_list:', verbose_name_list)
    print('\nname_list', name_list)
    field_names = verbose_name_list
    context = {'objects_values': objects_values, 'objects_values_list': objects_values_list,  'statics': statics, 'field_names': field_names}
    return render(request, 'table.html', context)

orm_abc_app/templates/abc_form.html
{% extends 'layout.html' %}

{% block title %} form_abc_app/abc_form {% endblock %}

{% block content %}
    <h5>orm_abc_app:abc_form</h5>
    <pre>
    https://docs.djangoproject.com/en/4.1/ref/forms/
    </pre>
{#    <form action="/abc_get" metod='get' target="_self">#}
    <form action="{% url 'orm_abc_app:abc_get' %}" metod='get' target="_self">
        {{ abc_form }}
        <label for="id_submit">&nbsp;</label>
        <button type="submit" id="id_submit">Отправить</button>
        </label>
    </form>
{% endblock %}

orm_abc_app/templates/abc_form_old.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

<form action="/abc_get" metod='get' target="_self">
    {{ abc_form }}
    <input type="submit">
</form>
</body>
</html>

orm_abc_app/templates/abc_result.html
{% extends 'layout.html' %}

{% block title %}orm_abc_app:result{% endblock %}

{% block content %}
    <h5>orm_abc_app:result</h5>
    <h6>{{ task_formulation }}</h6>
    <table class="table table-bordered">
        <thead>
        <tr>
            <th scope="col">X</th>
            <th scope="col">Y</th>
{#            <th scope="col">Z</th>#}
            <th scope="col">Результат</th>
        </tr>
        </thead>
        <tbody style="border-top: 0px;">
        <tr>
            {% for item in last_data %}
                <td>{{ item }}</td>
            {% endfor %}
            <td>{{ result }}</td>
        </tr>
{#        <tr>#}
{#            {% for key, value in last_object.items %}#}
{#                <td>{{ value }}</td>#}
{#            {% endfor %}#}
{#            <td>{{ result }}</td>#}
{#        </tr>#}
        </tbody>
    </table>
{% endblock %}

orm_abc_app/templates/datetime_now.html
{% extends 'layout.html' %}

{% block title %}
    orm_abc_app: date_time
{% endblock %}

{% block content %}
    <h5>orm_abc_app:date_time-content</h5>
    datetime_now: {{ key }}
{% endblock %}

orm_abc_app/templates/form_create.html
{% extends 'layout.html' %}

{% block title %} form_abc_app:form_create {% endblock %}

{% block content %}
    <h5>orm_abc_app:form_create</h5>
    {% load widget_tweaks %}
    <form {% url 'orm_abc_app:form_create' %} method="POST">
        {% csrf_token %}
        <div class="form-group mb-1">
            <div class="mb-1 row">
                <label class="col-sm-2 col-form-label">Формулировка</label>
                <div class="col-sm-10">
                    {% render_field form.task class="form-control" %}
                </div>
            </div>

            <div class="mb-1 row">
                <label class="col-sm-2 col-form-label">X</label>
                <div class="col-sm-10">
                    {% render_field form.x class="form-control" %}
                </div>
            </div>

            <div class="mb-1 row">
                <label class="col-sm-2 col-form-label">Y</label>
                <div class="col-sm-10">
                    {% render_field form.y class="form-control" %}
                </div>
            </div>

{#            <div class="mb-1 row">#}
{#                <label class="col-sm-2 col-form-label">Z</label>#}
{#                <div class="col-sm-10">#}
{#                    {% render_field form.z class="form-control" %}#}
{#                </div>#}
{#            </div>#}


            <div class="mb-1 row">
                <label class="col-sm-8 col-form-label"></label>
                <div class="col-sm-4 text-end">
                    <button type="submit" class="form-control">Отправить</button>
                </div>
            </div>
        </div>

    </form>
{% endblock %}

orm_abc_app/templates/form_create_0.html
{% extends 'layout.html' %}

{% block title %} form_abc_app/form_create_0 {% endblock %}

{% block content %}
    <h5>orm_abc_app:form_create_0</h5>
    <pre>
    https://docs.djangoproject.com/en/4.1/ref/forms/
    </pre>
    <form {% url 'orm_abc_app:form_create_0' %} method="POST">
        {% csrf_token %}
        {{ form }}
        <label for="id_submit">&nbsp;</label>
        <button type="submit" id="id_submit">Отправить</button>
        </label>
    </form>
{% endblock %}

orm_abc_app/templates/form_result.html
{% extends 'layout.html' %}

{% block title %}orm_abc_app:result{% endblock %}

{% block content %}
    <h5>orm_abc_app:result</h5>
    <pre>
    https://docs.djangoproject.com/en/4.1/contents/
    https://docs.djangoproject.com/en/4.1/ref/models/
    https://docs.djangoproject.com/en/4.1/ref/models/fields/
    https://docs.djangoproject.com/en/4.1/ref/models/options/
    https://docs.djangoproject.com/en/4.1/ref/models/querysets/
    https://docs.djangoproject.com/en/4.1/ref/models/expressions/
    https://docs.djangoproject.com/en/4.1/ref/models/conditional-expressions/#advanced-queries
    https://docs.djangoproject.com/en/4.1/ref/models/database-functions/
    </pre>
    <h6>{{ task_formulation }}</h6>
    <table class="table table-bordered">
        <thead>
        <tr>
            <th scope="col">A</th>
            <th scope="col">B</th>
            <th scope="col">C</th>
            <th scope="col">Результат</th>
        </tr>
        </thead>
        <tbody style="border-top: 0px;">
        <tr>
            {% for item in last_data %}
                <td>{{ item }}</td>
            {% endfor %}
            <td>{{ result }}</td>
        </tr>
        <tr>
            {% for key, value in last_object.items %}
                <td>{{ value }}</td>
            {% endfor %}
            <td>{{ result }}</td>
        </tr>
        </tbody>
    </table>
{% endblock %}

orm_abc_app/templates/index.html
{% extends 'layout.html' %}

{% block title %}
    orm_abc_app:index-title
{% endblock %}

{% block content %}
    <h5>orm_abc_app:index-content</h5>
    <pre>
    https://docs.djangoproject.com/en/4.1/ref/templates/
    https://docs.djangoproject.com/en/4.1/ref/templates/language/#variables
    https://docs.djangoproject.com/en/4.1/ref/templates/language/#tags
    </pre>
    <pre>
    https://docs.djangoproject.com/en/4.1/contents/
    https://docs.djangoproject.com/en/4.1/ref/models/
    https://docs.djangoproject.com/en/4.1/ref/models/fields/
    https://docs.djangoproject.com/en/4.1/ref/models/options/
    https://docs.djangoproject.com/en/4.1/ref/models/querysets/
    https://docs.djangoproject.com/en/4.1/ref/models/expressions/
    https://docs.djangoproject.com/en/4.1/ref/models/conditional-expressions/#advanced-queries
    https://docs.djangoproject.com/en/4.1/ref/models/database-functions/
    </pre>
{% endblock %}

orm_abc_app/templates/layout.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    {% load static %}
    <link href="{% static 'css/mycss.css' %}" rel="stylesheet">
    <title>{% block title %}{% endblock %}</title>
</head>

<div class="container">

    <div class="card">
        <div class="card-body bgc">
            {% load static %} <img src="{% static 'images/settings_django.png' %}"
                                   alt="settings_django" height="30px">
            <p>
            <pre>object-relational mapper</pre>
            </p>
        </div>
    </div>

    <div class="card">
        <div class="card-body">
            {% include "navigation.html" %}
        </div>
    </div>

    <div class="card">
        <div class="card-body">
            {% block content %}{% endblock %}
        </div>
    </div>

    <div class="card">
        <div class="card-body">
            Footer
        </div>
    </div>

</div>

<body>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>
</body>
</html>

orm_abc_app/templates/list_dict.html
{% extends 'layout.html' %}

{% block title %}orm_abc_app:var_list_dict{% endblock %}


{% block content %}
    <h5>var_list_dict</h5>
    <p> var_main: {{ var_main }}</p>
    <p>list_main: {{ list_main }}</p>
    <p>list_main.1: {{ list_main.1 }}</p>
    <ul>
        {% for value in list_main %}
            {% if  value == var_main %}
                <li>true: {{ value }}
                    {% else %}
                <li>else: {{ value }}
            {% endif %}
        {% endfor %}
    </ul>

    <p>dict_main</p>
    <ul>
        <li>{{ dict_main }}
        <li>{{ dict_main.x }}
        <li>{{ dict_main.y }}
            <ul>
                {% for key, value in dict_main.items %}
                    <li>{{ key }}: {{ value }}
                    {% if value == var_main %} - true_value
                    {% else %} - false_value
                    {% endif %}
                {% endfor %}
            </ul>
    </ul>
{% endblock %}

orm_abc_app/templates/navigation.html
<ul class="nav">
    <li class="nav-item"><a class="nav-link" href="{% url 'orm_abc_app:index' %}">orm_abc_app:index</a></li>
    <li class="nav-item"><a class="nav-link" href="{% url 'orm_abc_app:datetime_nov' %}">orm_abc_app:datetime_nov</a>
    <li class="nav-item"><a class="nav-link" href="{% url 'orm_abc_app:var_list_dict' %}">orm_abc_app:var_list_dict</a></li>
    <li class="nav-item"><a class="nav-link" href="{% url 'orm_abc_app:abc_form' %}">orm_abc_app:abc_form</a></li>
    <li class="nav-item"><a class="nav-link" href="{% url 'orm_abc_app:form_create_0' %}">orm_abc_app:form_create_0</a></li>
    <li class="nav-item"><a class="nav-link" href="{% url 'orm_abc_app:form_create' %}">orm_abc_app:form_create</a></li>
    <li class="nav-item"><a class="nav-link" href="{% url 'orm_abc_app:abc_result' %}">orm_abc_app:abc_result</a></li>
    <li class="nav-item"><a class="nav-link" href="{% url 'orm_abc_app:table' %}">orm_abc_app:table</a></li>
</ul>

orm_abc_app/templates/table.html
{% extends 'layout.html' %}

{% block title %}orm_abc_app:table{% endblock %}


{% block content %}
    <h5>orm_abc_app:table</h5>

    <table class="table table-bordered">
        <tbody style="border-top: 3.0px;">
        {% for object in objects_values %}
            <tr>
                {% for key, value in object.items %}
                    <td>
                        {{ value }}
                    </td>
                {% endfor %}
            </tr>
        {% endfor %}
        <tbody>
    </table>

    <table class="table table-bordered">
        <tbody style="border-top: 3.0px;">
        <tr>
            {% for name in field_names %}
                <td>{{ name }}</td>
            {% endfor %}
        </tr>
        {% for objects_values in objects_values_list %}
            <tr>
                {% for item in objects_values %}
                    <td>
                        {{ item }}
                    </td>
                {% endfor %}
            </tr>
        {% endfor %}
        <tbody>
    </table>

    <p>Статистика</p>
    {#    {% autoescape off %}{{ statics.statics_val }}{% endautoescape %}#}
    {% for item in statics.statics_val %}
        {% for k, v in  item.items %}
            {{ k }}:  {{ v }};
            {#            {% autoescape off %}{{ k }}:  {{ v }}; {% endautoescape %}#}
        {% endfor %}
    {% endfor %}


{% endblock %}